language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-28
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-21
jdk:
  - oraclejdk8

script:
 - gradle build connectedCheck

branches:
  only:
  - master
  - develop